triples = [
    [1, 'c',  'python',  'performance', 1],
    [2, 'petrol',  'diesel',  'energy', 0],
    [3, 'gold',  'copper',  'conductivity', 0],
    [4, 'aac',  'mp3',  'sound quality', 1],
    [5, 'earth',  'venus',  'mass', 1],
    [6, 'steel',  'aluminum',  'harder', 1],
    [7, 'swimming',  'running',  'calories', 0],
    [8, 'milk',  'soda',  'calories', 1],
    [9, 'usa',  'australia',  'size', 1],
    [10, 'gold',  'platinum',  'density', 0],
    [11, 'java',  'python',  'cross-platform', 0.5],
    [12, 'steel',  'aluminum',  'elastic', 0],
    [13, 'python',  'go',  'performance', 0],
    [14, 'lion',  'tiger',  'weight', 0],
    [15, 'ben hur',  'titanic',  'oscars', 0.5],
    [16, 'MLB',  'NBA',  'salaries', 0],
    [17, 'coal',  'oil',  'energy content', 0],
    [18, 'pennsylvania',  'michigan',  'weather', 1],
    [19, 'concrete',  'metal',  'durability', 1],
    [20, 'metal',  'concrete',  'ramps', 0],
    [21, 'maple',  'ash',  'harder', 1],
    [22, 'iron',  'copper',  'melting point', 1],
    [23, 'rowing',  'running',  'calories', 0],
    [24, 'galaxy s4',  'iphone 5',  'performance', 1],
    [25, 'germany',  'italy',  'life expectancy', 0],
    [26, 'windows 7',  'windows 8',  'boot time', 0],
    [27, 'porcelain',  'ceramic',  'more durable', 1],
    [28, 'plywood',  'lumber',  'strength', 0],
    [29, 'walnut',  'oak',  'harder', 0],
    [30, 'poland',  'portugal',  'average income', 0],
    [31, 'a380',  '747',  'wingspan', 1],
    [32, 'model s',  'i3',  'range', 1],
    [33, 'hamburg',  'venice',  'bridges', 1],
    [34, 'wii u',  'ps3',  'processor', 0]
]

evaluation_lists = {
    'c': ['c++', 'c++ performance', 'f', 'java', 'python', 'rust', 'cpp', 'go', 'c++ differences', 'c++ calling convention'],
    'petrol': ['diesel', 'diesel engine', 'diesel car', 'turquoise', 'gasoline', 'diesel price', 'gas', 'cng', 'petroleum', 'diesel car india'],
    'gold': ['platin', 'dollar', 'euro', 'silver', 'ld', 'bitcoin', 'bitcoin chart', 'rose gold', 'msci world', 'dax', ],
    'aac': ['mp3', 'aptx', 'ac3', 'flac', 'ogg', 'sbc', 'm4a', 'vorbis', 'dts', 'mp3 bitrate'],
    'earth': ['the spider', 'mars', 'the spider 2001', 'the flying saucers', 'jupiter', 'sun', 'moon size', 'sun size', 'earth', 'mars size'],
    'steel': ['iron', 'aluminum', 'aluminum bike', 'red', 'steal', 'stainless steel', 'alloy wheels', 'metal', 'titanium', 'cast iron'],
    'swimming': ['running', 'gym', 'running calories', 'walking', 'jogging', 'cycling', 'rowing', 'running cardio', 'running reddit', 'yoga'],
    'milk': ['yogurt', 'soy milk', 'cream', 'curd', 'buttermilk', 'egg', 'evaporated milk', 'water', 'melk', 'dark chocolate'],
    'usa': ['colombia', 'china', 'germany', 'russland', 'türkei', 'deutschland', 'russia', 'europe', 'brazil', 'maxico soccer'],
    'java': ['javascript', 'python', 'c++', 'kotlin', 'scala', 'java ee', 'python performance', 'php', 'go', '.net'],
    'python': ['java', 'julia', 'r', 'perl', 'c++', 'matlab', 'ruby', 'javascript', 'php', 'go'],
    'lion': ['tiger', 'bear', 'gorilla', 'crocodile', 'hyena', 'buffalo', 'wolf', 'hippo', 'dog'],
    'ben hur': ['lawrence of arabia', 'spartacus', 'the ten commandments', 'jesus', 'messala', 'the bible', 'esther', 'judah', 'the chariot race'],
    'MLB': ['nfl', 'nfl revenue', 'nba', 'japan', 'lhp', 'npb', 'nba salary', 'nfl ratings', 'american league', 'nhl'],
    'coal': ['charcoal', 'natural gas', 'coke', 'wood', 'oil', 'nuclear', 'solar', 'petroleum', 'diamond', 'charcoal minecraft'],
    'pennsylvania': ['mimms', 'ohio', 'new jersey', 'philadelphia', 'massachusetts', 'texas', 'maryland', 'california', 'virginia', 'nelson'],
    'concrete': ['cement', 'asphalt road', 'abstract', 'asphalt', 'abstract nouns', 'mortar', 'pavers', 'abstract thinking', 'cement slab', 'steel'],
    'metal': ['vulkan', 'opengl', 'rock', 'pop', 'opencl', 'punk', 'rap', 'lee', 'techno', 'rock lee'],
    'maple': ['mathematica', 'matrlab', 'rosewood', 'pau ferro', 'oak', 'birch', 'valnut', 'oak flooring', 'oak tree', 'ash bats'],
    'iron': ['steel', 'steamer', 'bronze', 'chrome', 'ferritin', 'cast iron', 'aluminum', 'folic acid', 'driver swing', 'metal'],
    'rowing': ['running', 'cycling', 'treadmill', 'kayaking', 'sculling', 'swimming', 'crew', 'running reddit', 'canoeing', 'biking'],
    'galaxy s4': ['s5', 's7', 's8', 'j5', 'a5 2017', 's6', 's5 mini', 's3', 'j7', 's9'],
    'germany': ['canada', 'france', 'sweden', 'peru', 'mexico', 'france 2018', 'brazil', 'usa', 'south korea', 'australia'],
    'windows 7': ['windows 10', 'windows 10 performance', 'windows 10 2018', 'windows 10 gaming', 'windows 8.1', 'windows 8', '10 gaming', 'windows 10 gaming performance', 'windows 10 performance 2018', 'windows xp'],
    'porcelain': ['ceramic', 'ceramic tiles', 'stoneware', 'china', 'marble', 'ceramic corwn', 'glass', 'ceramic mugs', 'ceramic plates', 'zirconia'],
    'plywood': ['mdf', 'osb', 'plyboard', 'solid wood', 'drawall', 'wood', 'osb subfloor', 'hardboard', 'mdf cabinets', 'pine'],
    'walnut': ['pecan', 'almond', 'oak', 'cherry', 'black walnut wood', 'black walnut', 'teak', 'hickory', 'peanut', 'cherry wood'],
    'poland': ['germany', 'italy', 'portugal', 'ireland', 'italy 2018', 'brazil', 'portugal 2018', 'portugal prediction', 'italy prediction', 'usa volleyball'],
    'a380': ['777', 'a320', '747', 'a350', '747-8', 'antonov', '787', 'antonov 124', 'an 225', 'dreamliner'],
    'model s': ['model 3', 'model x', 's class', 'model 3 reddit', 'i pace', 'model 3 price', 'hellcat', 'taycan', 'i8', 'roadster'],
    'hamburg': ['st pauli', 'berlin', 'munich', 'st pauli tickets', 'london', 'münchen', 'frankfurt', 'munich cost of living', 'bochum tickets', 'köln'],
    'wii u': ['switch', 'nintendo switch', 'wii', 'switch performance', 'switch specs', 'switch hardware', 'wii u premium', 'ps3', 'switch leistung', 'ps4'],
}

objects = ['MLB', 'a380', 'aac', 'ben hur', 'c', 'coal', 'concrete', 'earth', 'galaxy s4', 'germany', 'gold', 'hamburg', 'iron', 'java', 'lion', 'maple', 'metal',
           'milk', 'model s', 'pennsylvania', 'petrol', 'plywood', 'poland', 'porcelain', 'python', 'rowing', 'steel', 'swimming', 'usa', 'walnut', 'wii u', 'windows 7']
